# Generated by Django 5.2.4 on 2025-08-06 19:12

import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField()),
                ('team', models.CharField(max_length=300)),
                ('abstract', models.TextField(default='No abstract yet')),
                ('duration', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('scientific_case', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(verbose_name=projects.models.Author)),
                ('url', models.URLField(blank=True)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, upload_to='publications/files/')),
                ('image', models.ImageField(blank=True, upload_to='publications/images/')),
                ('type', models.CharField(choices=[('Journal', 'Journal Article'), ('Conference', 'Conference Paper'), ('Workshop', 'Workshop Paper'), ('Preprint', 'Preprint'), ('Thesis', 'Thesis/Dissertation'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Technical Report', 'Technical Report'), ('Patent', 'Patent'), ('Poster', 'Poster'), ('Abstract', 'Abstract'), ('Editorial', 'Editorial'), ('Review', 'Review Article'), ('Magazine', 'Magazine Article'), ('Blog', 'Blog Post'), ('White Paper', 'White Paper'), ('Dataset', 'Dataset'), ('Software', 'Software/Code'), ('Standard', 'Standard/Specification'), ('Symposium', 'Symposium'), ('Tutorial', 'Tutorial'), ('Keynote', 'Keynote Speech'), ('Invited Talk', 'Invited Talk'), ('Panel', 'Panel Discussion'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.TextField(default='No abstract yet')),
                ('collaborators', models.ManyToManyField(to='projects.author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_title', models.CharField(max_length=255)),
                ('match_score', models.FloatField()),
                ('match_authors', models.TextField()),
                ('approved', models.BooleanField(null=True)),
                ('project', models.ForeignKey(default=projects.models.get_default_project, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.publication')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_by_ai', models.BooleanField(default=True)),
                ('confirmed_by_admin', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.publication')),
            ],
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
