# Generated by Django 5.2.4 on 2025-08-07 00:30

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=200, verbose_name=projects.models.Author),
        ),
    ]
