# Generated by Django 5.2.4 on 2025-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_description_project_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('paper', models.FileField(blank=True, null=True, upload_to='publications/papers/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/')),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=50)),
                ('authors', models.TextField(help_text='List all authors separated by commas')),
            ],
        ),
    ]
