# Generated by Django 5.2.4 on 2025-07-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='paper',
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, upload_to='publications/files/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='publications/images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
