# Generated by Django 5.2.4 on 2025-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_publication_author_publication_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=100),
        ),
    ]
