# Generated by Django 5.2.4 on 2025-08-05 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_publication_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team',
            new_name='collaborators',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='collaborators',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(default='No abstract yet'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(default='No abstract yet'),
        ),
        migrations.AddField(
            model_name='publication',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HarvestMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_by_ai', models.BooleanField(default=True)),
                ('confirmed_by_admin', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.publication')),
            ],
        ),
    ]
