# Generated by Django 5.2.4 on 2025-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_matchrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchrequest',
            old_name='accepted',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='matchrequest',
            old_name='shared_authors',
            new_name='match_authors',
        ),
        migrations.RenameField(
            model_name='matchrequest',
            old_name='similarity',
            new_name='match_score',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='match_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='match_title',
            field=models.CharField(default='Unknown Title', max_length=255),
            preserve_default=False,
        ),
    ]
